providers:
  # Routers and Services are defined dynamically via Redis
  redis:
    rootKey: "traefik"
    endpoints:
      - "127.0.0.1:6379"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

