providers:
  #
  # Routers and Services are defined dynamically via Redis
  # (See app.config.ts sources, line 30~55)
  #
  redis:
    rootKey: "traefik"
    endpoints:
      - "127.0.0.1:6379"

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

